name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
            - الاسم: إعداد بيئة Node.js
  الاستخدامات: actions/setup-node@v5.0.0
  مع:
    # تعيين دائمًا المصادقة في npmrc.
    always-auth: # اختياري، الافتراضي هو false
    # مواصفات الإصدار المُراد استخدامه. أمثلة: 12.x، 10.15.1، >=10.15.0.
    إصدار العقدة: # اختياري
    # ملف يحتوي على مواصفات الإصدار المُراد استخدامه. أمثلة: package.json، .nvmrc، .node-version، .tool-versions.
    ملف إصدار العقدة: # اختياري
    # بنية النظام المستهدفة التي ستستخدمها العقدة. أمثلة: x86، x64. سيتم استخدام بنية النظام افتراضيًا.
    الهندسة المعمارية: # اختياري
    # قم بتعيين هذا الخيار إذا كنت تريد أن يتحقق الإجراء من أحدث إصدار متوفر يلبي مواصفات الإصدار.
    التحقق الأحدث: # اختياري
    # سجل اختياري لإعداد المصادقة. سيتم ضبط السجل في ملفي .npmrc و.yarnrc على مستوى المشروع، وإعداد المصادقة للقراءة من env.NODE_AUTH_TOKEN.
    عنوان URL للتسجيل: # اختياري
    # نطاق اختياري للمصادقة على السجلات المحددة. سيعود الأمر إلى مالك المستودع عند استخدام سجل حزم GitHub (https://npm.pkg.github.com/).
    النطاق: # اختياري
    # يُستخدم لسحب توزيعات العقد من إصدارات العقد. نظرًا لوجود قيمة افتراضية، عادةً لا يُقدّمها المستخدم. عند تشغيل هذا الإجراء على github.com، تكون القيمة الافتراضية كافية. عند التشغيل على GHES، يمكنك تمرير رمز وصول شخصي إلى github.com إذا كنت تواجه قيودًا على السرعة.
    الرمز المميز: # اختياري، الافتراضي هو ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # يُستخدم لتحديد مدير حزم للتخزين المؤقت في الدليل الافتراضي. القيم المدعومة: npm، yarn، pnpm.
    ذاكرة التخزين المؤقت: # اختياري
    # اضبط على "خطأ" لتعطيل التخزين المؤقت التلقائي بناءً على حقل مدير الحزم في package.json. افتراضيًا، يتم تفعيل التخزين المؤقت إذا كان حقل مدير الحزم موجودًا.
    package-manager-cache: # اختياري، الافتراضي هو true
    # يستخدم لتحديد المسار إلى ملف التبعية: package-lock.json، yarn.lock، وما إلى ذلك. يدعم الأحرف البدل أو قائمة بأسماء الملفات لتخزين التبعيات المتعددة مؤقتًا.
    مسار اعتماد ذاكرة التخزين المؤقت: # اختياري
    # يستخدم لتحديد مرآة بديلة لتنزيل ملفات Node.js الثنائية من
    المرآة: # اختياري
    # الرمز المستخدم كرأس تفويض عند جلب البيانات من المرآة
    رمز المرآة: # اختياري
          
